Repository myfreecomm/myfinance-client-ruby, pull requests merged in 2018-06, with the labels that each got.

#58 Add installment-related fields to Sale
  lib/myfinance/entities/sale.rb
  spec/lib/myfinance/entities/sale_spec.rb
Labels: enhancement, hold

#59 Add provider code to sales
  Gemfile.lock
  lib/myfinance/entities/sale.rb
  spec/lib/myfinance/entities/sale_spec.rb
Labels: enhancement, review

#60 Add sale-related fields for FA
  lib/myfinance/entities/financial_account.rb
  spec/lib/myfinance/entities/payable_account_spec.rb
  spec/lib/myfinance/entities/receivable_account_spec.rb
Labels: enhancement, next-release

#61 Add amount difference to Sales and expected deposit account to Sale Accounts
  lib/myfinance/entities/sale.rb
  lib/myfinance/entities/sale_account.rb
  spec/lib/myfinance/entities/sale_account_spec.rb
  spec/lib/myfinance/entities/sale_spec.rb
Labels: enhancement, review
